jenkins file changed

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -3,8 +3,14 @@ pipeline {
 
     environment {
         AWS_REGION = 'ap-south-2'
-        ECR_REPOSITORY = 'enterprise-app'
         AWS_ACCOUNT_ID = '705557196379'
+        ECR_REPOSITORY = 'enterprise-app'
+
+        CLUSTER_NAME = 'enterprise-product-eks'
+        NAMESPACE = 'enterprise'
+        DEPLOYMENT_NAME = 'enterprise-app'
+        CONTAINER_NAME = 'enterprise-app'
+
         IMAGE_TAG = "v${BUILD_NUMBER}"
         IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
     }
@@ -17,7 +23,7 @@ pipeline {
             }
         }
 
-        stage('Build') {
+        stage('Build Application') {
             steps {
                 dir('app') {
                     sh 'mvn clean package'
@@ -25,7 +31,7 @@ pipeline {
             }
         }
 
-        stage('Unit Tests') {
+        stage('Run Unit Tests') {
             steps {
                 dir('app') {
                     sh 'mvn test'
@@ -36,39 +42,96 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 dir('app') {
-                    sh 'docker build -t enterprise-app:${IMAGE_TAG} .'
+                    sh """
+                    docker build \
+                    -t ${ECR_REPOSITORY}:${IMAGE_TAG} .
+                    """
                 }
             }
         }
 
         stage('Login to Amazon ECR') {
             steps {
-                sh '''
+                sh """
                 aws ecr get-login-password --region ${AWS_REGION} | \
                 docker login \
                 --username AWS \
                 --password-stdin ${IMAGE_URI}
-                '''
+                """
             }
         }
 
-        stage('Push Image to ECR') {
+        stage('Push Docker Image') {
             steps {
-                sh '''
-                docker tag enterprise-app:${IMAGE_TAG} ${IMAGE_URI}:${IMAGE_TAG}
+                sh """
+                docker tag ${ECR_REPOSITORY}:${IMAGE_TAG} ${IMAGE_URI}:${IMAGE_TAG}
                 docker push ${IMAGE_URI}:${IMAGE_TAG}
-                '''
+                """
             }
         }
+
+        stage('Update kubeconfig') {
+            steps {
+                sh """
+                aws eks update-kubeconfig \
+                  --region ${AWS_REGION} \
+                  --name ${CLUSTER_NAME}
+                """
+            }
+        }
+
+        stage('Deploy to Amazon EKS') {
+            steps {
+                sh """
+                kubectl set image deployment/${DEPLOYMENT_NAME} \
+                ${CONTAINER_NAME}=${IMAGE_URI}:${IMAGE_TAG} \
+                -n ${NAMESPACE}
+                """
+            }
+        }
+
+        stage('Verify Rollout') {
+            steps {
+                sh """
+                kubectl rollout status deployment/${DEPLOYMENT_NAME} \
+                -n ${NAMESPACE}
+                """
+            }
+        }
+
+        stage('Verify Pods') {
+            steps {
+                sh """
+                kubectl get pods -n ${NAMESPACE}
+                kubectl get svc -n ${NAMESPACE}
+                """
+            }
+        }
+
     }
 
     post {
 
         success {
-            echo "Pipeline completed successfully."
+            echo '==============================================='
+            echo 'Build Successful'
+            echo "Docker Image : ${IMAGE_URI}:${IMAGE_TAG}"
+            echo 'Application deployed successfully to Amazon EKS'
+            echo '==============================================='
+        }
+
+        failure {
+            echo '==============================================='
+            echo 'Build or Deployment Failed'
+            echo '==============================================='
         }
 
         always {
+            sh """
+            docker image rm -f ${ECR_REPOSITORY}:${IMAGE_TAG} || true
+            docker image rm -f ${IMAGE_URI}:${IMAGE_TAG} || true
+            docker image prune -f || true
+            """
             cleanWs()
         }
     }
